default:
    pattern:  /
    defaults: { _controller: BorrowersIssueBundle:Issue:current }

BorrowersIssueBundle:
    resource: "@BorrowersIssueBundle/Controller/"
    type:     annotation
    prefix:   /

BorrowersHomeBundle:
    resource: "@BorrowersHomeBundle/Controller/"
    type:     annotation
    prefix:   /

BorrowersUserBundle:
    resource: "@BorrowersUserBundle/Controller/"
    type:     annotation
    prefix:   /
    
Reroute:
    pattern:  /cocoon/borrowers/
    resource: "@BorrowersIssueBundle/Controller/"
    type:     annotation

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

_user_bundle:
    resource: "@BorrowersUserBundle/Resources/config/routing.yml"
    