default:
    pattern:  /
    defaults: { _controller: BorrowersIssueBundle:Issue:current }

BorrowersIssueBundle:
    resource: "@BorrowersIssueBundle/Controller/"
    type:     annotation
    prefix:   /

BorrowersHomeBundle:
    resource: "@BorrowersHomeBundle/Controller/"
    type:     annotation
    prefix:   /

BorrowersUserBundle:
    resource: "@BorrowersUserBundle/Controller/"
    type:     annotation
    prefix:   /
    
_user_bundle:
    resource: "@BorrowersUserBundle/Resources/config/routing.yml"
    