default:
    pattern:  /
    defaults: { _controller: BorrowersIssueBundle:Issue:current }

BorrowersIssueBundle:
    resource: "@BorrowersIssueBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    