## YAML Template.
services:
    namer.upload_file:
        class: AppBundle\Namer\Namer
        tags:
            - { name: namer }
    directory_namer.upload_file:
        class: AppBundle\Namer\DirectoryNamer
        tags:
            - { name: directory_namer }