<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileRepository extends EntityRepository
{
    public function findRecentFiles()
    {  
       return $this->getEntityManager()
               ->createQuery('SELECT f from AppBundle:File f ORDER BY f.created DESC')
               ->setMaxResults(25)->getResult();
    } 
}