<?php

namespace Borrowers\IssueBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AuthorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorRepository extends EntityRepository
{
    public function listAuthors()
    {
        $repostitory = $this->getEntityManager()->getRepository('BorrowersIssueBundle:Author');
        $query = $repostitory->createQueryBuilder('a')
                ->orderBy('a.lastname','ASC')
                ->getQuery();
        return  $query->getResult();
    }
}