<?php

namespace Borrowers\IssueBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * IssueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IssueRepository extends EntityRepository
{
    public function listIssues()
    {
        $repostitory = $this->getEntityManager()->getRepository('BorrowersIssueBundle:Issue');
        $query = $repostitory->createQueryBuilder('i')
                ->orderBy('i.created','DESC')
                ->getQuery();
        return  $query->getResult();
    }
    

}